### ISSUE TITLE
Refactoring with interfaces

### ISSUE THREAD

**Issue by ABIOLI-COM** [KristofferStrube/Blazor.SVGEditor#10]
Kristoffer,  
    your work has been really impressive, in this project.  

In particular, I found it incredibly useful to use the editor for Bezier curves, in a project I'm working on.  

![image](https://user-images.githubusercontent.com/63686917/236817037-33e503d3-2f7c-4f8a-9e03-bc9fe9770a24.png)

My only (small) concern is that I had to create a new SVG element, removing all the things I don't need. I attach the resulting set of projects, where you can see that I had to duplicate a lot of other classes, because creating an SVG2 element, there is a strong dependency on the concrete class in other elements.  
I'm wondering if it could be possible to refactor things a little bit to make things cleaner... I'm available to help, if you want...

[Blazor.SVGEditor.zip](https://github.com/KristofferStrube/Blazor.SVGEditor/files/11420803/Blazor.SVGEditor.zip)

**Comment by KristofferStrube** [comment]
Hey @ABIOLI-COM awesome that you found the project useful once again. 😁

I've been thinking of releasing the project as a NuGet package and making all features configurable and togglable which I think is what you have tried to achieve by copying the `SVG`, `Path`, `Shape`, etc. classes.
This is a list of the things I would like to be configurable on the `SVG` component so that people don't need to modify (or copy) it. If you have any other things that you would like to be configurable or be able to toggle off then please note so. 😀

- [x] Disable/enable context menu
- [x] Disable/enable zoom
- [x] Disable/enable panning
- [x] Disable/enable deselecting elements
- [x] Disable/enable selecting elements
- [x] Disable/enable window marking of multiple shaped
- [x] Disable anchors and lines (basically meaning disabling shape edits)
- [x] Add/remove/reorder/replace all individual menu items.
- [x] Add/remove shape handlers
- [x] Add/remove animation handlers
- [x] Change primary and secondary colors for anchors, striped lines, scalar boxes, and the background.

All of the above would then be configurable but with the defaults that are the current ones. What do you think of this and are there any settings that you would be missing for your use case?

_I'm updating the above checklist as I add support for configuring each part._

**Comment by KristofferStrube** [comment]
@ABIOLI-COM I have released the project to NuGet now with features that should make it more configurable so that you don't have to do source code copying. Here is a link to the NuGet package: https://www.nuget.org/packages/KristofferStrube.Blazor.SVGEditor

You can check out two examples of how to use this here:
https://kristofferstrube.github.io/Blazor.SVGEditor/Minimal/
https://kristofferstrube.github.io/Blazor.SVGEditor/CustomElements/

If you would like to test using it in one of your projects then I would be very happy to get any feedback you might have.
